### PR TITLE
feat(macos): basic package and group handling

### PR DESCRIPTION
**Pull request by noelmcloughlin**
PR adding basic package & group handling (see https://github.com/saltstack/salt/issues/53325) on MacOS.

### CODE REVIEW

**Comment by myii** [comment]
@noelmcloughlin You may be interested in a tiny refactor I added to this change in the [`template-formula`](https://github.com/saltstack-formulas/template-formula/pull/133).  The potential mix-up with the `*BSD`s needed to be avoided, I felt.

**Comment by noelmcloughlin** [comment]
[Let's discuss this at your PR](https://github.com/saltstack-formulas/template-formula/pull/133).

**Comment by myii** [comment]
[My comment there is just as significant here!](https://github.com/saltstack-formulas/template-formula/pull/133#issuecomment-497777350)

**Comment by noelmcloughlin** [comment]
Resolves #1

**Comment by noelmcloughlin** [comment]
Hi @myii I have updated PR to align with template-formula. thanks

**Comment by myii** [comment]
Thanks @noelmcloughlin.  I thought it would be good to wait for a review from @alxwr since he's the `rootgroup` expert!

**Comment by noelmcloughlin** [comment]
Hi @alxwr could you review please when you get time. 

Sorry ,I did'nt have permission to add reviewers to this and the grafana PR.

**Comment by myii** [comment]
@noelmcloughlin Actually, we can't select reviewers (or even merge) until write access is enabled on this repo.  I've made a request on Slack, so it should be done soon.

**Comment by noelmcloughlin** [comment]
Aah yeah, no merge button!!! he he.

**Comment by myii** [comment]
@noelmcloughlin Done (and requested `grafana-formula` as well).

**Comment by noelmcloughlin** [comment]
thanks @aboe and @myii

**Comment by myii** [comment]
@alxwr I didn't realise you've become the `semantic-release` bot!  Don't worry, I've just modified the Travis settings to give the permissions to the real bot.  We shouldn't have this problem going forward.

**Pull request merged**
