### PR TITLE
fix(config): cope with aberrant service names

### PR DESCRIPTION
**Pull request by alxwr**
This is a mergable solution to the concerns raised in #19.
Tested in Ubuntu 16.04.

### CODE REVIEW

**Comment by scambra** [comment]
I think config/args/clean.sls needs same change as config/args/install.sls

**Comment by alxwr** [comment]
@scambra Thanks for pointing this one out! Changed it.

**Comment by aboe76** [comment]
@alxwr thanks for this, merged it.

**Comment by alxwr** [comment]
@aboe76 Thanks for the merge!

**Pull request merged**
