### PR TITLE
Fix node_exporter service not restarted on archive fresh install

### PR DESCRIPTION
**Pull request by n-rodriguez**
### PR progress checklist (to be filled in by reviewers)

- [ ] Changes to documentation are appropriate (or tick if not required)
- [ ] Changes to tests are appropriate (or tick if not required)
- [ ] Reviews completed

---

#### Primary type

- [ ] `[build]`    Changes related to the build system
- [ ] `[chore]`    Changes to the build process or auxiliary tools and libraries such as documentation generation
- [ ] `[ci]`       Changes to the continuous integration configuration
- [ ] `[feat]`     A new feature
- [x] `[fix]`      A bug fix
- [ ] `[perf]`     A code change that improves performance
- [ ] `[refactor]` A code change that neither fixes a bug nor adds a feature
- [ ] `[revert]`   A change used to revert a previous commit
- [ ] `[style]`    Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc.)

#### Secondary type

- [ ] `[docs]`     Documentation changes
- [x] `[test]`     Adding missing or correcting existing tests

### Does this PR introduce a `BREAKING CHANGE`?

No.

### Describe the changes you're proposing

Fix https://github.com/saltstack-formulas/prometheus-formula/issues/42

### Documentation checklist

- [ ] Updated the `README` (e.g. `Available states`).
- [ ] Updated `pillar.example`.

### Testing checklist

- [ ] Included in Kitchen (i.e. under `state_top`).
- [ ] Covered by new/existing tests (e.g. InSpec, Serverspec, etc.).
- [ ] Updated the relevant test pillar.

### CODE REVIEW

**Review by noelmcloughlin — CHANGES_REQUESTED** [review]
Some CI problems.
```
  ×  prometheus services: should be running (3 failed)
     ×  Service node_exporter is expected to be enabled
     expected that `Service node_exporter` is enabled
     ×  Service node_exporter is expected to be running
     expected that `Service node_exporter` is running
     ×  Port 9100 is expected to be listening
     expected `Port 9100.listening?` to return true, got false
```

**Comment by n-rodriguez** [comment]
> Some CI problems.

I think there's something wrong here : https://github.com/saltstack-formulas/prometheus-formula/blob/master/prometheus/service/running.sls#L15

**Comment by noelmcloughlin** [comment]
> I think there's something wrong here : https://github.com/saltstack-formulas/prometheus-formula/blob/master/prometheus/service/running.sls#L15

That looks weird alright. All those `get` `get`?

**Comment by n-rodriguez** [comment]
>  All those `get` `get`?

Yes. I think test pass because it eventually fallbacks to default.

**Comment by n-rodriguez** [comment]
I've reverted my changes, here everything pass : https://travis-ci.com/github/n-rodriguez/prometheus-formula 
except 
* repo-debian-10-3000-3-py3
* repo-centos-7-3000-3-py3

To fix this https://travis-ci.com/github/n-rodriguez/prometheus-formula/jobs/376955959#L3608 I need to fix https://github.com/saltstack-formulas/prometheus-formula/blob/master/prometheus/service/running.sls#L15

**Comment by n-rodriguez** [comment]
```sh
# repo mode
[INFO    ] before: prometheus
[INFO    ] after: prometheus
[INFO    ] before: alertmanager
[INFO    ] after: prometheus-alertmanager
[INFO    ] before: node_exporter
[INFO    ] after: prometheus-node-exporter


# archive mode
[INFO    ] before: prometheus
[INFO    ] after: prometheus
[INFO    ] before: alertmanager
[INFO    ] after: alertmanager
[INFO    ] before: node_exporter
[INFO    ] after: prometheus-node-exporter
```

**Comment by n-rodriguez** [comment]
The bug in `archive mode` is due to https://github.com/saltstack-formulas/prometheus-formula/blob/master/pillar.example#L96

Test pillars should not be linked to `default.sls -> ../../../pillar.example`. 

IMHO `pillar.example` is part of documentation, not test. Documentation must evolve without breaking tests.

A good duplication is better than a bad abstraction.

**Comment by javierbertoli** [comment]
@n-rodriguez tests have their own pillars, in the `test/salt/pillar/`directoy and used [here](https://github.com/saltstack-formulas/prometheus-formula/blob/master/kitchen.yml#L166) and [here](https://github.com/saltstack-formulas/prometheus-formula/blob/master/kitchen.yml#L185).

I think the 1st one was copied from `pillar.example`, but you can change it to whatever you consider is needed for testing.

**Comment by n-rodriguez** [comment]
> @n-rodriguez tests have their own pillars

sure, but `default.sls` is a symlink to `pillar.example`. this is the issue.

**Comment by javierbertoli** [comment]
> sure, but `default.sls` is a symlink to `pillar.example`. this is the issue.

oh, you're right! I didn't notice. Agreed, they should be separate files.

**Comment by n-rodriguez** [comment]
it's almost done : https://travis-ci.com/github/n-rodriguez/prometheus-formula/builds/181153407

**Comment by n-rodriguez** [comment]
The CentOS build (https://travis-ci.com/github/n-rodriguez/prometheus-formula/jobs/377069988) fails because test pillars are designed for Debian 

```yml
      node_exporter:
        version: v0.18.1
        archive:
          source_hash: b2503fd932f85f4e5baf161268854bf5d22001869b84f00fd2d1f57b51b72424
        service:
          name: prometheus-node-exporter
```

In CentOS services are named like the formula (or what I call archive mode) :
* node_exporter
* alertmanager

```sh
[root@6e589f384c81 kitchen]# systemctl list-unit-files
UNIT FILE                              STATE   
proc-sys-fs-binfmt_misc.automount      static  
dev-hugepages.mount                    static  
dev-mqueue.mount                       static  
proc-sys-fs-binfmt_misc.mount          static  
sys-fs-fuse-connections.mount          static  
sys-kernel-config.mount                static  
sys-kernel-debug.mount                 static  
tmp.mount                              disabled
systemd-ask-password-console.path      static  
systemd-ask-password-wall.path         static  
run-263.scope                          static  
run-264.scope                          static  
run-275.scope                          static  
run-302.scope                          static  
run-326.scope                          static  
run-350.scope                          static  
run-384.scope                          static  
run-397.scope                          static  
session-149.scope                      static  
alertmanager.service                   disabled
arp-ethers.service                     disabled
autovt@.service                        enabled 
blackbox_exporter.service              disabled
blk-availability.service               disabled
console-getty.service                  disabled
console-shell.service                  disabled
container-getty@.service               static  
dbus-org.freedesktop.hostname1.service static  
dbus-org.freedesktop.import1.service   static  
dbus-org.freedesktop.locale1.service   static  
dbus-org.freedesktop.login1.service    static  
dbus-org.freedesktop.machine1.service  static  
dbus-org.freedesktop.timedate1.service static  
dbus.service                           static  
debug-shell.service                    disabled
dracut-cmdline.service                 static  
dracut-initqueue.service               static  
dracut-mount.service                   static  
dracut-pre-mount.service               static  
dracut-pre-pivot.service               static  
dracut-pre-trigger.service             static  
dracut-pre-udev.service                static  
dracut-shutdown.service                static  
emergency.service                      static  
fstrim.service                         static  
getty@.service                         enabled 
halt-local.service                     static  
initrd-cleanup.service                 static  
initrd-parse-etc.service               static  
initrd-switch-root.service             static  
initrd-udevadm-cleanup-db.service      static  
kmod-static-nodes.service              static  
messagebus.service                     static  
node_exporter.service                  disabled
prometheus.service                     enabled 
quotaon.service                        static  
rc-local.service                       static  
rdisc.service                          disabled
rescue.service                         static  
rsyncd.service                         disabled
rsyncd@.service                        static  
salt-minion.service                    disabled
salt-proxy@.service                    disabled
serial-getty@.service                  disabled
sshd-keygen.service                    static  
sshd.service                           enabled 
sshd@.service                          static  
systemd-ask-password-console.service   static  
systemd-ask-password-wall.service      static  
systemd-backlight@.service             static  
systemd-binfmt.service                 static  
systemd-bootchart.service              disabled
systemd-firstboot.service              static  
systemd-fsck-root.service              static  
systemd-fsck@.service                  static  
systemd-halt.service                   static  
systemd-hibernate-resume@.service      static  
systemd-hibernate.service              static  
systemd-hostnamed.service              static  
systemd-hwdb-update.service            static  
systemd-hybrid-sleep.service           static  
systemd-importd.service                static  
systemd-initctl.service                static  
systemd-journal-catalog-update.service static  
systemd-journal-flush.service          static  
systemd-journald.service               static  
systemd-kexec.service                  static  
systemd-localed.service                static  
systemd-logind.service                 static  
systemd-machine-id-commit.service      static  
systemd-machined.service               static  
systemd-modules-load.service           static  
systemd-nspawn@.service                disabled
systemd-poweroff.service               static  
systemd-quotacheck.service             static  
systemd-random-seed.service            static  
systemd-readahead-collect.service      enabled 
```

**Comment by n-rodriguez** [comment]
Tests pass : https://travis-ci.com/github/saltstack-formulas/prometheus-formula :fireworks:

**Review by noelmcloughlin — APPROVED** [review]
Great PR. Well done @n-rodriguez

**Comment by myii** [comment]
Lovely work, @n-rodriguez.  Thanks for the reviews and feedback @noelmcloughlin and @javierbertoli!

**Pull request merged**
