### PR TITLE
Fix access to variables inside templates

### PR DESCRIPTION
**Pull request by viq**
Nested `{{ }}` is not supported, instead the variables need to be
accessed directly

This addresses #24 

### PR progress checklist (to be filled in by reviewers)

- [ ] Changes to documentation are appropriate (or tick if not required)
- [ ] Changes to tests are appropriate (or tick if not required)
- [ ] Reviews completed

---

#### Primary type

- [ ] `[build]`    Changes related to the build system
- [ ] `[chore]`    Changes to the build process or auxiliary tools and libraries such as documentation generation
- [ ] `[ci]`       Changes to the continuous integration configuration
- [ ] `[feat]`     A new feature
- [x] `[fix]`      A bug fix
- [ ] `[perf]`     A code change that improves performance
- [ ] `[refactor]` A code change that neither fixes a bug nor adds a feature
- [ ] `[revert]`   A change used to revert a previous commit
- [ ] `[style]`    Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc.)

#### Secondary type

- [ ] `[docs]`     Documentation changes
- [ ] `[test]`     Adding missing or correcting existing tests

### Does this PR introduce a `BREAKING CHANGE`?

No.

### Related issues and/or pull requests

#24 

### Describe the changes you're proposing

Using nested `{{ }}` inside templates is not supported, instead they need to be accessed directly and concatenation used.

### Pillar / config required to test the proposed changes

```
prometheus:
  tofs:
    source_files:
      prometheus-archive-install-node_exporter-managed-service:
        - node_exporter.service.jinja
```

### Debug log showing how the proposed changes work

```
[DEBUG   ] In saltenv 'base', looking at rel_path 'prometheus/libtofs.jinja' to resolve 'salt://prometheus/libtofs.jinja'
[DEBUG   ] In saltenv 'base', ** considering ** path '/var/cache/salt/minion/files/base/prometheus/libtofs.jinja' to resolve 'salt://prometheus/libtofs.jinja'
[DEBUG   ] LazyLoaded config.get
[DEBUG   ] key: prometheus:tofs:path_prefix, ret: _|-
[DEBUG   ] key: prometheus:tofs:dirs:files, ret: _|-
[DEBUG   ] key: prometheus:tofs:files_switch, ret: _|-
[DEBUG   ] key: prometheus:tofs:files:prometheus-archive-install-prometheus-managed-service, ret: _|-
[DEBUG   ] key: prometheus:tofs:source_files:prometheus-archive-install-prometheus-managed-service, ret: _|-
[DEBUG   ] key: prometheus:files_switch, ret: _|-
[DEBUG   ] key: prometheus:tofs:dirs:default, ret: _|-
[DEBUG   ] key: prometheus:tofs:path_prefix, ret: _|-
[DEBUG   ] key: prometheus:tofs:dirs:files, ret: _|-
[DEBUG   ] key: prometheus:tofs:files_switch, ret: _|-
[DEBUG   ] key: prometheus:tofs:files:prometheus-archive-install-node_exporter-managed-service, ret: _|-
[DEBUG   ] key: prometheus:files_switch, ret: _|-
[DEBUG   ] key: prometheus:tofs:dirs:default, ret: _|-
[DEBUG   ] key: prometheus:tofs:dirs:default, ret: _|-
[DEBUG   ] key: prometheus:tofs:path_prefix, ret: _|-
[DEBUG   ] key: prometheus:tofs:dirs:files, ret: _|-
[DEBUG   ] key: prometheus:tofs:files_switch, ret: _|-
[DEBUG   ] key: prometheus:tofs:files:prometheus-archive-install-alertmanager-managed-service, ret: _|-
[DEBUG   ] key: prometheus:tofs:source_files:prometheus-archive-install-alertmanager-managed-service, ret: _|-
[DEBUG   ] key: prometheus:files_switch, ret: _|-
[DEBUG   ] key: prometheus:tofs:dirs:default, ret: _|-
```

### Documentation checklist

- [ ] Updated the `README` (e.g. `Available states`).
- [ ] Updated `pillar.example`.

### Testing checklist

- [ ] Included in Kitchen (i.e. under `state_top`).
- [ ] Covered by new/existing tests (e.g. InSpec, Serverspec, etc.).
- [ ] Updated the relevant test pillar.

### CODE REVIEW

**Comment by myii** [comment]
@viq Thanks for raising the issues and this PR.  Noticed your messages in IRC but didn't get to respond to you at the time.

In terms of the underlying issue, I can confirm that there is a problem.

* https://travis-ci.com/saltstack-formulas/prometheus-formula/jobs/246554551#L1166-L1172
* https://travis-ci.com/saltstack-formulas/prometheus-formula/jobs/246554551#L1187-L1193

The alternate `source` path set in the pillar isn't being used.

---

In terms of fixing this, I'd like to go in a slightly different direction and also fix the use of `files_switch` throughout the formula.

* https://github.com/myii/prometheus-formula/compare/103b55f9566d...341fff36ead5
  - Apart from the change to `use_upstream_archive: true`, that was just for the purpose of running tests.

This is now working as expected, throughout the formula:

* https://travis-ci.org/myii/prometheus-formula/jobs/624002053#L1154-L1166
* https://travis-ci.org/myii/prometheus-formula/jobs/624002053#L1219-L1231
* https://travis-ci.org/myii/prometheus-formula/jobs/624002053#L1638-L1650
* https://travis-ci.org/myii/prometheus-formula/jobs/624002053#L1665-L1677

Would you be able to confirm this at your end, @viq?

**Comment by viq** [comment]
In conversation I was asked to provide a use case. Currently, in early stages, what I'm trying to achieve is:
* install components from archives instead of system packages, because I want them new but I'm currently running this on old ubuntu
* prometheus server, listening only on loopback (`--web.listen-address="127.0.0.1:9100"` added to service flags)
* alertmanager set up, probably also for now listening only on loopback
* node exporter set up, possibly with additional flags passed (textfile directory, for one)

Eventually it'd be great if I could also with this set up https://github.com/prometheus/cloudwatch_exporter/

**Comment by viq** [comment]
Current issues that don't work with the above scenario:
1. Flags added by the formula end up not being used. From my reading that's how it happens:
* they get written to "args file"
* "args file" is not read by anything.
The flags need to be either added directly to start up command, or the files need to be sourced.

2. Start up command is hardcoded. While it works with `prometheus` and `alertmanager`, for example `node_exporter` does not recognize `--config.file` option and refuses to start. The start commands need to be customised for existing exporters, and/or customisable by the user as needed.
3. It would be wonderful to be able to add custom exporters, at least the simple ones, passing information like:
* where to get the executable of the exporter
* potentially what dependencies are to be installed with it (though that can get hairy, and I guess can be left as an exercise to the user)
* what command to use to start the exporter, what other flags to pass to it

**Comment by myii** [comment]
Based upon our discussions in Slack/IRC, the current proposal is to use the `lookup` with the `name` included.  So with the current pillar, the states will be:

* `prometheus-archive-install-prometheus-managed-service`
* `prometheus-archive-install-node_exporter-managed-service`
* `prometheus-config-file-prometheus-file-managed`
* `prometheus-config-file-node_exporter-file-managed`

Leading to the `tofs` entry in the pillar to be something similar to:

```yaml
  tofs:
    ...
    source_files:
      prometheus-archive-install-prometheus-managed-service
        - 'prometheus_systemd.ini.jinja'
      prometheus-archive-install-node_exporter-managed-service
        - 'node_exporter_systemd.ini.jinja'
      prometheus-config-file-prometheus-file-managed
        - 'prometheus_config.yml.jinja'
      prometheus-config-file-node_exporter-file-managed
        - 'node_exporter_config.yml.jinja'
```

**Comment by baby-gnu** [comment]
As a matter of style, I wonder if gathering all complicated string manipulations couldn't be better regarding [recommendations](https://docs.saltstack.com/en/latest/topics/development/conventions/formulas.html), something like:

```diff
diff --git a/prometheus/archive/install.sls b/prometheus/archive/install.sls
index a60090f..1ac3c5d 100644
--- a/prometheus/archive/install.sls
+++ b/prometheus/archive/install.sls
@@ -24,16 +24,25 @@ prometheus-config-file-basedir-file-directory:
   {%- for name in p.wanted %}
       {%- if name in p.pkg %}
           {%- set bundle = name + '-%s.%s-%s'|format(p.pkg[name]['archive_version'], p.kernel, p.arch) %}
+          {%- set archive_dir = p.dir.basedir %}
+          {%- set archive_source = p.archive.uri | path_join(name,
+                                                             'releases',
+                                                             'download',
+                                                             v ~ p.pkg[name]['archive_version'],
+                                                             bundle ~ '.' ~ p.archive.suffix
+                                                             ) %}
+          {%- set archive_hash = p.pkg[name]['archive_hash'] %}
+
+          {%- set archive_kwargs = p.archive.kwargs %}
 
 prometheus-archive-install-{{ name }}-archive-extracted:
   archive.extracted:
-    - name: {{ p.dir.basedir }}
-    - source: {{ p.archive.uri }}/{{ name }}/releases/download/v{{ p.pkg[name]['archive_version']
-                 + '/' + bundle + '.' + p.archive.suffix }}
-    - source_hash: {{ p.pkg[name]['archive_hash'] }}
+    - name: {{ archive_dir }}
+    - source: {{ archive_source }}
+    - source_hash: {{ archive_hash }}
     - user: {{ name }}
     - group: {{ name }}
-    {{- format_kwargs(p.archive.kwargs) }}
+    {{- format_kwargs(archive_kwargs) }}
     - recurse:
         - user
         - group
@@ -41,10 +50,16 @@ prometheus-archive-install-{{ name }}-archive-extracted:
       - file: prometheus-config-file-basedir-file-directory
 
           {%- if name in p.service %}
+              {%- set workdir = p.dir.var | path_join(name) %}
+              {%- set service_filename = p.dir.service | path_join(name ~ '.service') %}
+
+              {%- set exec_name = p.dir.basedir | path_join(bundle, name) %}
+              {%- set config_filename = p.dir.etc | path_join(name ~ '.yml') %}
+              {%- set start_cmd  =  exec_name ~ ' --config.file ' ~ config_filename
 
 prometheus-archive-install-{{ name }}-file-directory:
   file.directory:
-    - name: {{ p.dir.var }}/{{ name }}
+    - name: {{ workdir }}
     - user: {{ name }}
     - group: {{ name }}
     - mode: 755
@@ -57,9 +72,9 @@ prometheus-archive-install-{{ name }}-file-directory:
 
 prometheus-archive-install-{{ name }}-managed-service:
   file.managed:
-    - name: {{ p.dir.service }}/{{ name }}.service
+    - name: {{ service_name }}
     - source: {{ files_switch(['systemd.ini.jinja'],
-                              lookup='prometheus-archive-install-managed-service'
+                              lookup='prometheus-archive-install-' ~ name ~ '-managed-service'
                  )
               }}
     - mode: 644
@@ -72,8 +87,8 @@ prometheus-archive-install-{{ name }}-managed-service:
         name: {{ name }}
         user: {{ name }}
         group: {{ name }}
-        workdir: {{ p.dir.var }}/{{ name }}
-        start: {{ p.dir.basedir }}/{{ bundle }}/{{ name }} --config.file {{ p.dir.etc }}/{{ name }}.yml
+        workdir: {{ workdir }}
+        start: {{ start_cmd }}
         stop: '' #not needed
     - require:
       - file: prometheus-archive-install-{{ name }}-file-directory
```

Creating simple variables make it easier to modify the structure of ``p`` if required.

NB:
* this style modification should be a dedicated commit and not mixed with the fix
* it's better to use `~` for [string concatenation](https://jinja.palletsprojects.com/en/2.10.x/templates/#other-operators) but this diff does not replace them all.

**Comment by noelmcloughlin** [comment]
@viq @myii @baby-gnu 
I created #30 to align with template formula, semantic release, improve CI/CD coverage, add support for client libs, and hopefully address some issues raised in the discussions. My PR does not address TOFS.  

Regarding string manipulations  ... the template-formula and community have no published opinion or consensus on how diverse packaging (archive files, homebrew, mac app, snapcraft, formats) and unbounded software ecosystems like Prometheus might be handled.  In this vacuum, I find string manipulations absolutely essential for reusable patterns across unrelated formulas - if there is no common pattern for archives/homebrew/snap/packages/repos across hundreds of formulas then it is almost impossible for CODEOWNERS to do their job in a reasonable effort.  

Comments in https://github.com/saltstack-formulas/prometheus-formula/pull/25#issuecomment-565038325 should be converted to issue.
- the args stuff seems to be FreeBSD related (sysrc)
- the command line args are not really supported.
- Prometheus is a demanding subject  - more PRs will be needed in future.

Once #30 is merged we could revisit wishlist

**Comment by noelmcloughlin** [comment]
#30 is merged now.  Comments in #25 (comment) should be converted to issue.

**Comment by noelmcloughlin** [comment]
Fixed in recent merged PRs.
https://github.com/saltstack-formulas/prometheus-formula/blob/aad810fa6aa53075d9154f36ada9f97be32eff66/prometheus/archive/install.sls#L102

**Pull request closed without merging**
