### PR TITLE
refactor(id): rename yaml dict 'component' to 'comp'

### PR DESCRIPTION
**Pull request by noelmcloughlin**
### PR progress checklist (to be filled in by reviewers)

- [x] Changes to documentation are appropriate (or tick if not required)
- [x] Changes to tests are appropriate (or tick if not required)
- [ ] Reviews completed

---

#### Primary type

- [ ] `[build]`    Changes related to the build system
- [ ] `[chore]`    Changes to the build process or auxiliary tools and libraries such as documentation generation
- [ ] `[ci]`       Changes to the continuous integration configuration
- [ ] `[feat]`     A new feature
- [ ] `[fix]`      A bug fix
- [ ] `[perf]`     A code change that improves performance
- [x] `[refactor]` A code change that neither fixes a bug nor adds a feature
- [ ] `[revert]`   A change used to revert a previous commit
- [ ] `[style]`    Changes that do not affect the meaning of the code (white-space, formatting, missing semi-colons, etc.)

#### Secondary type

- [ ] `[docs]`     Documentation changes
- [ ] `[test]`     Adding missing or correcting existing tests

### Does this PR introduce a `BREAKING CHANGE`?

No.

### Describe the changes you're proposing

This PR renames "component" dict to "comp" just to shorten the name.
The `map.jinja` includes code to handle existing pillar data containing "component".

### Documentation checklist

- [ ] Updated the `README` (e.g. `Available states`).
- [ ] Updated `pillar.example`.

### Testing checklist

- [ ] Included in Kitchen (i.e. under `state_top`).
- [x] Covered by new/existing tests (e.g. InSpec, Serverspec, etc.).
- [ ] Updated the relevant test pillar.

### CODE REVIEW

**Comment by javierbertoli** [comment]
@noelmcloughlin , this _**IS**_ a breaking change, did you just forgot to mark it as such?

**Comment by n-rodriguez** [comment]
@noelmcloughlin what's the point of this PR?

**Comment by noelmcloughlin** [comment]
> this _**IS**_ a breaking change, did you just forgot to mark it as such?

I had updated `map.jinja` to avoid breaking change:
```
## Legacy pillars support ('component' renamed to 'comp) ##
{%- if 'component' in prometheus.wanted and prometheus.wanted.component %}
    {%- do prometheus.wanted.update({'comp': prometheus.wanted.component }) %}
{%- endif %}
{%- if 'component' in prometheus.pkg and prometheus.pkg.component %}
    {%- do prometheus.pkg.update({'comp': prometheus.pkg.component }) %}
{%- endif %}
## Legacy (remove me after 31/4/21) ##
```

**Comment by noelmcloughlin** [comment]
> what's the point of this PR?

It's opinionated but pointless otherwise. Happy to close it.

**Pull request closed without merging**
